
################################################################################
##################### JRC's version using libcbm_runner ########################
################################################################################
# Data preparation: 
# Copy the 


# Import
from libcbm_runner.core.continent import continent

# Init
scenario = continent.scenarios['historical']
runner_libcbm = scenario.runners['LU'][-1]
runner_libcbm.run()

# Show results
#print(runner_libcbm.simulation.results)
#print(runner_libcbm.simulation.inventory)

# Retrieve pools
pools_libcbm = runner_libcbm.simulation.results.pools

# Make dataframe
merch_libcbm_by_year = (pools_libcbm
  .groupby('timestep')
  .agg({'HardwoodMerch': 'sum',
        'SoftwoodMerch': 'sum'})
  .reset_index())

# Show
print(merch_libcbm_by_year)

#      timestep  HardwoodMerch  SoftwoodMerch
# 0           0   6.541837e+06   3.742087e+06

###############################################################################
################ Canada's version using only libcbm_py ########################
###############################################################################

# Imports
from libcbm.input.sit import sit_cbm_factory
from libcbm.model.cbm import cbm_simulator
import os

# Constants
# Uses the json file generated by the above code
json_config_path = "/home/paul/rp/libcbm_data/scenarios/historical/LU/0/input/json/config.json"
db_path = "/home/paul/repos/libcbm_data/countries/LU/orig/config/aidb.db"

# Function
def run_libcbm():
    #libcbm_config_path = os.path.abspath(json_config_path)
    libcbm_config_path = json_config_path
    sit = sit_cbm_factory.load_sit(libcbm_config_path, db_path)
    classifiers, inventory = sit_cbm_factory.initialize_inventory(sit)
    cbm = sit_cbm_factory.initialize_cbm(sit)
    results, reporting_func = cbm_simulator.create_in_memory_reporting_func()
    rule_based_processor = sit_cbm_factory.create_sit_rule_based_processor(sit, cbm)
    cbm_simulator.simulate(
        cbm,
        n_steps              = 102,
        classifiers          = classifiers,
        inventory            = inventory,
        pool_codes           = sit.defaults.get_pools(),
        flux_indicator_codes = sit.defaults.get_flux_indicators(),
        pre_dynamics_func    = rule_based_processor.pre_dynamic_func,
        reporting_func       = reporting_func
    )
    return results

# Run libcbm
libcbm_results = run_libcbm()

# Make dataframe
libcbm_merch_by_timestep = libcbm_results.pools[
    ["timestep", "SoftwoodMerch", "HardwoodMerch"]
].groupby("timestep").sum().rename(
    columns={
        "timestep": "TimeStep",
        "SoftwoodMerch": "swm_libcbm",
        "HardwoodMerch": "hwm_libcbm"
    })

# Show
print(libcbm_merch_by_timestep)

#             swm_libcbm    hwm_libcbm
# timestep
# 0         3.742087e+06  6.541837e+06

